### ISSUE TITLE
ECONNREFUSED 47.94.164.49:10332

### ISSUE THREAD

**Issue by zeshanvirk** [CityOfZion/neo-js#148]
usign this Code

const Node = require('@cityofzion/neo-js');
 const nodeT = new Node({ network: 'testnet' }) 

nodeT.mesh.getBlock(10).then(res=>{

  console.log(res);

}).catch(err=>{

  console.log(err);
});

Error: connect ECONNREFUSED 47.94.164.49:10332
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '47.94.164.49',
  port: 10332,
  config:
   { adapter: [Function: httpAdapter],
     transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     timeout: 10000,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     headers:
      { Accept: 'application/json, text/plain, */*',
        'Content-Type': 'application/json;charset=utf-8',
        'User-Agent': 'axios/0.16.2',
        'Content-Length': 60 },
     method: 'post',
     url: 'http://seed1.neo.org:10332',
     data: '{"jsonrpc":"2.0","method":"getblock","params":[10,1],"id":0}' },
  request:
   Writable {
     _writableState:
      WritableState {
        objectMode: false,
        highWaterMark: 16384,
        needDrain: false,
        ending: false,
        ended: false,
        finished: false,
        decodeStrings: true,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: true,
        bufferProcessing: false,
        onwrite: [Function],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: false,
        errorEmitted: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [Object] },
     writable: true,
     domain: null,
     _events:
      { response: [Function: handleResponse],
        error: [Function: handleRequestError] },
     _eventsCount: 2,
     _maxListeners: undefined,
     _options:
      { protocol: 'http:',
        maxRedirects: 21,
        maxBodyLength: 10485760,
        hostname: 'seed1.neo.org',
        port: '10332',
        path: '/',
        method: 'post',
        headers: [Object],
        agent: undefined,
        auth: undefined,
        nativeProtocols: [Object],
        pathname: '/' },
     _redirectCount: 0,
     _requestBodyLength: 60,
     _requestBodyBuffers: [ [Object] ],
     _onNativeResponse: [Function],
     _currentRequest:
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 6,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedHeader: [Object],
        _contentLength: null,
        _hasBody: true,
        _trailer: '',
        finished: false,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'POST / HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nContent-Type: application/json;charset=utf-8\r\nUser-Agent: axios/0.16.2\r\nContent-Length: 60\r\nHost: seed1.neo.org:10332\r\nConnection: close\r\n\r\n',
        _headers: [Object],
        _headerNames: [Object],
        _onPendingData: null,
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'POST',
        path: '/',
        _ended: false,
        _redirectable: [Circular],
        parser: null },
     _currentUrl: 'http://seed1.neo.org:10332/' },
  response: undefined }

**Comment by rockacola** [comment]
We are pending for a new release very soon, that may address this concern. Alternatively, you may choose to target at `develop` branch for the bleeding edge implementations.

**Comment by rockacola** [comment]
Provided example is out of date, a better example has been pending for next release.

Please try the following example code:

```
const Neo = require('@cityofzion/neo-js');
const neo = new Neo({ network: 'testnet' })

setTimeout(() => {
    neo.mesh.getBlock(10)
        .then(res => {
            console.log(res);
        }).catch(err => {
            console.log(err);
        });
}, 5000)
```

**Comment by zeshanvirk** [comment]
When is the expected release??

Also its limited library, how can i create wallet, generate addresses, send&sign transactions?? 

i tried to define some custome methods as you defined in library but i got Access Denied Error, while hitting the api, is there any other package to use for this purpose? i'm developing an exchange and i want to integrate neo in it and want to create wallet, generate addresses, send&sign transactions, without using any third party library which have charges!!

**Comment by rockacola** [comment]
It looks like you are after `neon-js` project.

**Comment by zeshanvirk** [comment]
no. neon-js project doesn't allow us to create wallet and generate new addresses. which is most important.
