### ISSUE TITLE
neo.storage.getAssetBalance err

### ISSUE THREAD

**Issue by gengxuelei** [CityOfZion/neo-js#156]
neo.storage.getAssetBalance(addr, kacHash)
https://github.com/CityOfZion/neo-js/blob/develop/examples/smoke-test/asset.js
```
05:53:00.234 Storage error: getExpandedTX Promise.all err: TypeError: Cannot read property 'vout' of null
    at tx.vin._.map (C:\atest\neo-js\dist\node\storage.js:314:48)
    at arrayMap (C:\atest\neo-js\node_modules\lodash\lodash.js:631:23)
    at Function.map (C:\atest\neo-js\node_modules\lodash\lodash.js:9546:14)
    at Promise.all.then (C:\atest\neo-js\dist\node\storage.js:314:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
05:59:14.478 examples:rpc-endpoints info: assetBalance: { asset: '0x602c79718b16e442de58778e148d0b1084e3b2dffd5de6b7b16cee7969282de7',
  balance: 72411.84199755987,
  index: 148065,
  type: 'a' }
```

**Comment by rockacola** [comment]
Cannot replicate the said error in the coming `0.8.0` release. 
Shall the error persists for you in the coming `0.8.0`, please resubmit an issue with relevant debugging information (per issue template).
