### ISSUE TITLE
Primary entry point missing in npm package

### ISSUE THREAD

**Issue by ThomasLobker** [CityOfZion/neo-js#163]
## Primary entry point missing in npm package

* **`neo-js` Version**: 0.8.0
* **`node` Version**: 10
* **Operation System**: Ubuntu
* **MongoDB Version** (if applicable): any

## Expected behavior

Being able to require `@cityofzion/neo-js` after `npm i @cityofzion/neo-js`
```const Node = require('@cityofzion/neo-js');```

## Actual behavior

```internal/modules/cjs/loader.js:573
    throw err;
    ^

Error: Cannot find module '@cityofzion/neo-js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (index.js:1:76)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
```

## Steps to reproduce the behavior

1. `npm i @cityofzion/neo-js`
2. `echo "const Node = require('@cityofzion/neo-js');" > index.js`
3. `nodejs index.js`

**Comment by rockacola** [comment]
:+1:
