### ISSUE TITLE
Unhandled exception when there are no valid nodes

### ISSUE THREAD

**Issue by ThomasLobker** [CityOfZion/neo-js#165]
## Context (Environment)

* **`neo-js` Version**: `0.8.1`
* **`node` Version**: `v10.2.1`
* **Operation System**: `Ubuntu 18.04 LTS`
* **MongoDB Version** (if applicable): `version v3.6.3`

## Expected behavior

When all nodes are unavailable I'm expecting the synchronization to stop temporarily until nodes become available again.

## Actual behavior

First I'm getting a clean error message notifying that there are no more valid nodes, then the whole script is crashing with the following error message:

```11:41:05.926 SyncStrategy error: Unable to find a valid node.
/usr/local/src/neo-js/node_modules/@cityofzion/neo-js/dist/strategy/sync-strategy.js:224
    const max = node.index || index
                     ^

TypeError: Cannot read property 'index' of undefined
    at SyncStrategy.enqueueBlock (/usr/local/src/neo-js/node_modules/@cityofzion/neo-js/dist/strategy/sync-strategy.js:224:22)
    at Timeout.setTimeout [as _onTimeout] (/usr/local/src/neo-js/node_modules/@cityofzion/neo-js/dist/strategy/sync-strategy.js:115:18)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
```

## Steps to reproduce the behavior

1. Run `neo-js` as a full node
1. Wait for a day or so, until there is a moment where no more nodes are responsive
1. Or disconnect your network (haven't tried it, but I assume this will trigger it as well)

**Comment by rockacola** [comment]
Legacy issue from `<=0.8.1`.
