### ISSUE TITLE
TypeError: x is not a function

### ISSUE THREAD

**Issue by yinqianwu** [CityOfZion/neo-js#43]
I am trying to follow the instruction and run the code below.
```
var neo = require('neo-js-blockchain');
var neoBlockchain = neo('light', 'mainnet');
neoBlockchain.sync.start();

var node = require('./neo.blockchain.node.js');
var n = node({'domain': 'http://seed1.neo.org', 'port': 10332});
node.getBestBlockHash();
```
 but I got TypeError: x is not a function error. Can anyone give me a hint?
```
var neoBlockchain = neo('light', 'mainnet');
                    ^
TypeError: neo is not a function

n.getBestBlockHash();
  ^
TypeError: n.getBestBlockHash is not a function
```

**Comment by hmcq6** [comment]
Hey @yinqianwu, this looks like an issue with the way the `neo` function was exported. If you take a look at [neo.blockchain.node.js](https://github.com/CityOfZion/neo-js/blob/master/dist/neo.blockchain.neo.js#L80) it appears that `require('neo-js-blockchain')` will return an object instead of a function.

The object returned by the require statement has  has the signature
```JavaScript
{
  neo: function() { ... }
}
```

For now, I believe if you changed the first line to

```JavaScript
var neo = require('neo-js-blockchain').neo;
```

it should work. At least until this issue is resolved

**Comment by lllwvlvwlll** [comment]
var blockchainNeo = new neo.neo('light', 'mainnet');
blockchainNeo.sync.start();

**Comment by yinqianwu** [comment]
Thanks! Unfortunately, I got a new error.

```
/home/ubuntu/workspace/node_modules/neo-js-blockchain/dist/neo.blockchain.node.js:365
          params[scriptHash, params],
                ^

SyntaxError: Unexpected token [
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at new neo (/home/ubuntu/workspace/node_modules/neo-js-blockchain/dist/neo.blockchain.neo.js:20:15)
```
